Issue 59 discovery ignoring measurement
testable-eu/sast-tp-framework pull request #61
Opened 2023-05-15 15:16 UTC by compaluca

Fixes #59: discovery can be run ignoring the SAST measurement

2023-05-16 09:42 UTC, felix-20 requested changes

2023-05-16 09:42 UTC, felix-20 commented on tp_framework/core/utils.py
> +        return list(filter(lambda p: get_id_from_name(p.name) == pattern_id, list_dirs_only(tp_lib_dir_lang_dir)))[0]
```suggestion
       pattern_with_id = list(filter(lambda p: get_id_from_name(p.name) == pattern_id, list_dirs_only(tp_lib_dir_lang_dir)))
        if pattern_with_id:
            return pattern_with_id[0]
    raise PatternDoesNotExists(pattern_id)
```
The if statement only checks if the `tp_lib_dir_lang_dir` exists. But what if the wanted pattern ID in the directory does not exist? The current version will throw a `KeyError` there. I think a `PatternDoesNotExist` Exception is a little bit more descriptive and additionally, this matches the result expected in `qualitytests/core/test_utils.py`

2023-05-16 09:42 UTC, felix-20 commented on tp_framework/core/utils.py
> +    return list(filter(lambda tpi_dir: get_id_from_name(tpi_dir.name) == instance_id, l_pattern_dir))[0]
```suggestion
    instance_with_id = list(filter(lambda tpi_dir: get_id_from_name(tpi_dir.name) == instance_id, l_pattern_dir))
    if not instance_with_id:
        raise InstanceDoesNotExists()
    return instance_with_id[0]
```
This suggestion follows the same argumentation as the comment above. If there is no instance with the wanted ID, the current version throws a `KeyError`.  This suggestion would throw an `InstanceDoesNotExists()` error.

2023-05-16 09:42 UTC, felix-20 commented on tp_framework/core/utils.py
> +    DiscoveryMethodNotSupported, TargetDirDoesNotExist, InvalidSastTool, PatternFolderNotFound
```suggestion
    DiscoveryMethodNotSupported, TargetDirDoesNotExist, InvalidSastTool, PatternFolderNotFound, InstanceDoesNotExists

```

Is related to the comments below.

2023-05-16 09:42 UTC, felix-20 commented on tp_framework/core/discovery.py
> +    d_tpi_discovery = {}
```suggestion
    d_tpi_discovery = dict.fromkeys(["rule_path", "method", "rule_name", "rule_accuracy", "rule_hash", \
                                     "rule_name", "results", "rule_already_executed"], None)
```
This makes the code a bit shorter and assures, that the dict contains all necessary keys in all branching cases

2023-05-16 09:42 UTC, felix-20 commented on tp_framework/core/discovery.py
> +        d_tpi_discovery["results"] = None
```suggestion
        # no rule to execute
        d_tpi_discovery["rule_already_executed"] = False
```
With the changes from above, we could get rid of all these lines and replace it just with the `d_tpi_discovery["rule_already_executed"] = False` line

2023-05-16 09:42 UTC, felix-20 commented on tp_framework/core/utils.py
Unfortunately Github will not allow me to add a comment to code, that has not been changed, so this comment refers to `tpframework/core/utils.py:get_path_or_none()`

```python
def get_path_or_none(p: str) -> Path | None:
    if p:
        return Path(p)
    return None
```

The current version of the function looks like this:

```python
def get_path_or_none(p: str) -> Path | None:
    if p not None:
        return Path(p)
    return p
```
In my opinion, the problem with this function is, that it will not return what you would expect, if `p=""` is passed to the function. If `p` is an empty string, the if condition `if p is not None` will evaluate to `True` which means, that the return value of the function is `Path(".")`.  This is not what I would expect. Additionally the tool might fail with this, i.e. `tpframework discovery -t testability_patterns/PHP/5_combined_operator/ -p 5 -l php --ignore-measurements` throws an error for me.

2023-05-16 09:42 UTC, felix-20 commented on qualitytests/core/test_discovery.py
Here, a test can be included, capturing the problem, when an instance has no discovery rule given.


```python
def test_dicovery_with_empty_rule(self):
        with open(join_resources_path("sample_patlib/PHP/4_empty_pattern/4_empty_pattern.json"), "r") as json_file:
            pattern_dict = json.load(json_file)
        test_pattern = pattern.pattern_from_dict(pattern_dict, "PHP", 4)
        with open(join_resources_path("sample_patlib/PHP/4_empty_pattern/1_instance_4_empty_pattern/1_instance_4_empty_pattern.json"), "r") as json_file:
            instance_dict = json.load(json_file)
        tpi_instance = instance.instance_from_dict(instance_dict, test_pattern, "PHP", 1)
        assert not tpi_instance.discovery_rule, "The test case is broken, instance 1 of PHP pattern 4 is not supposed to have a discovery rule"

        expected = dict.fromkeys(["rule_path", "method", "rule_name", "rule_accuracy", "rule_hash", "rule_name", "results", "rule_already_executed"], None)
        expected["rule_already_executed"] = False

        actual = discovery.discovery_for_tpi(tpi_instance, None, None, None)
        assert expected == actual
```

2023-05-16 09:56 UTC, felix-20 commented on qualitytests/core/test_discovery.py
Test and necessary files are implemented in 72fd2c0

2023-05-17 14:11 UTC, compaluca commented on tp_framework/core/utils.py
done

2023-05-17 14:12 UTC, compaluca commented on qualitytests/core/test_discovery.py
tested and works fine

2023-05-17 14:12 UTC, merged